[package]
name = "ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.8.3"
plotters = "0.3.5"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.26.0"
objc = "0.2.7"
